orc:
    url: http://127.0.0.1:8080/
    user: admin
    pass: admin

vars:
    x: 100::109

p2p:
    -
        name: p2p_$x_A
        si:
            -
                switch: EdgeCore5610-100
                port: 4
                vlan: $x+100
                secondVlan: 10
            -
                switch: EdgeCore5610-101
                port: 4
                vlan: $x+200
                secondVlan: 11
    -
        name: p2p_$x_B
        si:
            -
                switch: EdgeCore5610-99
                port: 1
                vlan: $x+300
                secondVlan: 12
            -
                switch: EdgeCore5610-101
                port: 4
                vlan: $x+400
                secondVlan: 13
m2m:
    -
        name: m2m_$x
        si:
            -
                switch: EdgeCore5610-99
                port: 1
                vlan: $x+500
                secondVlan: 14
                defaultInterface: True
            -
                switch: EdgeCore5610-101
                port: 4
                vlan: $x+600
                secondVlan: 15
            -
                switch: EdgeCore5610-100
                port: 4
                vlan: $x+700
                secondVlan: 16
p2m:
    -
        name: p2m_$x
        si:
            -
                switch: EdgeCore5610-99
                port: 1
                vlan: $x+800
                secondVlan: 14
                defaultInterface: True
                role: ROOT
            -
                switch: EdgeCore5610-101
                port: 4
                vlan: $x+900
                secondVlan: 15
            -
                switch: EdgeCore5610-100
                port: 4
                vlan: $x+1000
                secondVlan: 16