orc:
    url: http://10.255.148.110:8080/
    user: admin
    pass: admin

vars:
    x: 100::199

p2p:
    -
        name: p2p_$x_A
        si:
            -
                switch: SW5610-100
                port: 4
                vlan: $x
                secondVlan: $x
            -
                switch: SW5610-101
                port: 4
                vlan: $x
                secondVlan: $x
    -
        name: p2p_$x_B
        si:
            -
                switch: SW5610-100
                port: 4
                vlan: $x+100
                secondVlan: $x+100
            -
                switch: SW5610-101
                port: 4
                vlan: $x+100
                secondVlan: $x+100
m2m:
    -
        name: m2m_$x
        si:
            -
                switch: SW5610-100
                port: 4
                vlan: $x+200
                secondVlan: $x+200
                defaultInterface: True
            -
                switch: SW5610-101
                port: 4
                vlan: $x+200
                secondVlan: $x+200
            -
                switch: SW4610-95
                port: 2
                vlan: $x+200
                secondVlan: $x+200
p2m:
    -
        name: p2m_$x
        si:
            -
                switch: SW5610-100
                port: 4
                vlan: $x+300
                secondVlan: $x+300
                defaultInterface: True
                role: ROOT
            -
                switch: SW5610-101
                port: 4
                vlan: $x+300
                secondVlan: $x+300
            -
                switch: SW4610-95
                port: 2
                vlan: $x+300
                secondVlan: $x+300