orc:
    url: http://127.0.0.1:8080/
    user: admin
    pass: admin

vars:
    x: 100::199

p2p:
    -
        name: p2p_$x_A
        si:
            -
                switch: SW1
                port: 1
                vlan: $x
                secondVlan: $x
            -
                switch: SW2
                port: 1
                vlan: $x
                secondVlan: $x
    -
        name: p2p_$x_B
        si:
            -
                switch: SW3
                port: 1
                vlan: $x+100
                secondVlan: $x+100
            -
                switch: SW4
                port: 1
                vlan: $x+100
                secondVlan: $x+100
m2m:
    -
        name: m2m_$x
        si:
            -
                switch: SW1
                port: 2
                vlan: $x+200
                secondVlan: $x+200
                defaultInterface: True
                reserveSI :
                    switch: SW2
                    port: 2
                    vlan: $x+1200
            -
                switch: SW2
                port: 2
                vlan: $x+200
                secondVlan: $x+200
            -
                switch: SW3
                port: 2
                vlan: $x+200
                secondVlan: $x+200
p2m:
    -
        name: p2m_$x
        si:
            -
                switch: SW1
                port: 3
                vlan: $x+300
                secondVlan: $x+300
                defaultInterface: True
                role: ROOT
                reserveSI :
                    switch: SW1
                    port: 1
                    vlan: $x+1200
                    secondVlan: $x+1200
            -
                switch: SW2
                port: 3
                vlan: $x+300
                secondVlan: $x+300
            -
                switch: SW3
                port: 3
                vlan: $x+300
                secondVlan: $x+300