orc: [10.0.0.1, 10.0.0.2]
# use any
vars:
    x: "[100, 101, 102]"
    y: "range(1,10)"
    z: "range(1,10)"

# p2p and p2m rotated x*y*z times
p2p:
    name: p2p_$x
    si:
        -
            switch: 1
            port: 2
            tagType: 3
            vlan: $x
            secondVlan: $y
        -
            switch: 1
            port: 2
            tagType: 3
            vlan: $x
            secondVlan: $y
p2m:
    name: p2m_$x
    si:
        -
            switch: 1
            port: 2
            tagType: 3
            vlan: 1-100
            secondVlan: 2-4
        -
            switch: 1
            port: 2
            tagType: 3
            vlan: 1-100
            secondVlan: 2-4