orc: 10.0.0.1

vars:
    x: 1-5
    y: 1-10
    z: 1-90

p2p:
    name: p2p_$x_$y
    si:
        -
            switch: sw1
            port: 2
            vlan: $x
            secondVlan: $y
        -
            switch: sw2
            port: 2
            vlan: $x
            secondVlan: $y
p2m:
    name: p2m_$x_$y
    si:
        -
            switch: sw3
            port: 2
            vlan: $x
            secondVlan: $y
        -
            switch: sw4
            port: 2
            vlan: $x
            secondVlan: $y